### PR TITLE
Redesigned the entire website

### PR DESCRIPTION
**Pull request by GarkGarcia**
This is a follow up to https://github.com/mathics/mathics.github.io/issues/8.

### CODE REVIEW

**Review by rocky — COMMENTED** [review]
I don't feel qualified to comment on site design kinds of things.

If you and others like this go for it. 

You might solicit feedback on https://groups.google.com/g/mathics-users for comments.

**Comment by GarkGarcia** [comment]
>  don't feel qualified to comment on site design kinds of things.

No problem. I'm more concerned with the contents of page, though. I've changed it substantially, could you take a look?

**Comment by GarkGarcia** [comment]
Just so you guys don't need to pull the branch for revising it, here's a screenshot of the entire webpage:

Screenshot_2020-12-28 Mathics

**Comment by GarkGarcia** [comment]
And here's how it looks on mobile:

Screenshot_2020-12-28 Mathics(1)

**Comment by rocky** [comment]
I looked at the content and don't see anything wrong there. 

I vaguely thing think this is helpful. Thinking about it in this way - what it it people will want when they hit here

* What is mathics? 
* ok, how do I get it? 
* What I do if I have a problem?
* How do I contribute? 
* credits to all the software used


However in terms of design I am can't comment on. _And I strongly suggest you solicit feedback from the community._   Has that been done? If you want me to post something to the newsgroup or slack because you don't want to join them okay. But let me know in that case.

Of couse, as happens a lot here, if there is no feedback just assume agreement and move on.

**Comment by GarkGarcia** [comment]
> * How do I contribute?
> 
> * credits to all the software used

Thanks for the suggestions! Just wrote small sections on those points.

> However in terms of design I am can't comment on. _And I strongly suggest you solicit feedback from the community._ Has that been done? If you want me to post something to the newsgroup or slack because you don't want to join them okay. But let me know in that case.

I haven't posted anything in the newsgroup or slack. Could you take care of that? I don't have a Google/Slack account. I'll post something about this in our maintainers group too.

**Comment by rocky** [comment]
> > * How do I contribute?
> > * credits to all the software used
> 
> Thanks for the suggestions! Just wrote small sections on those points.
> 
> > However in terms of design I am can't comment on. _And I strongly suggest you solicit feedback from the community._ Has that been done? If you want me to post something to the newsgroup or slack because you don't want to join them okay. But let me know in that case.
> 
> I haven't posted anything in the newsgroup or slack. Could you take care of that? I don't have a Google/Slack account. I'll post something about this in our maintainers group too.

I will do this within a day or so.

**Comment by GarkGarcia** [comment]
@rocky @mmatera It looks like there hasn't been any activity at https://groups.google.com/g/mathics-users/c/OQ_Ex4Erhlg. Maybe we should merge this?

**Comment by rocky** [comment]
Ok by me.

**Pull request merged**
